#ifndef MESSAGETYPES_H
#define MESSAGETYPES_H
#include <QString>
enum class MessageType{
    DELETE_OLD_IP_AND_PORT,
    REQUEST_XML_PARAMETERS_FROM_SERVER,
    SUCCESSFULLY_CONNECTED_TO_SERVER,
    CANT_CONNECT_TO_SERVER,
    CLIENT_IP_ADDRESS,
    CLIENT_PORT,
    MESSAGE_FROM_SERVER,
    TRY_TO_CONNECT_TO_SERVER,
    DELETE_SOCKET_WRAPPER_THREAD,

};


namespace TextMessageType {
const QString dataRequestFromClientText = "Data, please";
}
#endif // MESSAGETYPES_H
